services:
    db:
        image: mysql:8
        restart: always
        env_file:
        - .env
        expose:
        - "3306"
        ports:
        - "3306:3306"
        volumes:
        - db:/var/lib/mysql
volumes:
  db: